// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: proto/config_ClassicalCombines.proto

#include "proto/config_ClassicalCombines.pb.h"

#include <algorithm>
#include "google/protobuf/io/coded_stream.h"
#include "google/protobuf/extension_set.h"
#include "google/protobuf/wire_format_lite.h"
#include "google/protobuf/descriptor.h"
#include "google/protobuf/generated_message_reflection.h"
#include "google/protobuf/reflection_ops.h"
#include "google/protobuf/wire_format.h"
#include "google/protobuf/generated_message_tctable_impl.h"
// @@protoc_insertion_point(includes)

// Must be included last.
#include "google/protobuf/port_def.inc"
PROTOBUF_PRAGMA_INIT_SEG
namespace _pb = ::google::protobuf;
namespace _pbi = ::google::protobuf::internal;
namespace _fl = ::google::protobuf::internal::field_layout;
namespace ClassicalCombines {
namespace pb {
        template <typename>
PROTOBUF_CONSTEXPR classical_combine_config::classical_combine_config(::_pbi::ConstantInitialized)
    : _impl_{
      /*decltype(_impl_.id_)*/ 0u,
      /*decltype(_impl_.controlflag_)*/ 0u,
      /*decltype(_impl_.combine0_)*/ ::uint64_t{0u},
      /*decltype(_impl_.combine1_)*/ ::uint64_t{0u},
      /*decltype(_impl_.rivaltype_)*/ 0u,
      /*decltype(_impl_.remainbigcount_)*/ 0u,
      /*decltype(_impl_.combine2_)*/ ::uint64_t{0u},
      /*decltype(_impl_._cached_size_)*/ {},
    } {}
struct classical_combine_configDefaultTypeInternal {
  PROTOBUF_CONSTEXPR classical_combine_configDefaultTypeInternal() : _instance(::_pbi::ConstantInitialized{}) {}
  ~classical_combine_configDefaultTypeInternal() {}
  union {
    classical_combine_config _instance;
  };
};

PROTOBUF_ATTRIBUTE_NO_DESTROY PROTOBUF_CONSTINIT
    PROTOBUF_ATTRIBUTE_INIT_PRIORITY1 classical_combine_configDefaultTypeInternal _classical_combine_config_default_instance_;
        template <typename>
PROTOBUF_CONSTEXPR classical_base_combine::classical_base_combine(::_pbi::ConstantInitialized)
    : _impl_{
      /*decltype(_impl_.bigcount_)*/ 0u,
      /*decltype(_impl_.bombcount_)*/ 0u,
      /*decltype(_impl_.triplecount_)*/ 0u,
      /*decltype(_impl_.paircount_)*/ 0u,
      /*decltype(_impl_.singlecount_)*/ 0u,
      /*decltype(_impl_._cached_size_)*/ {},
    } {}
struct classical_base_combineDefaultTypeInternal {
  PROTOBUF_CONSTEXPR classical_base_combineDefaultTypeInternal() : _instance(::_pbi::ConstantInitialized{}) {}
  ~classical_base_combineDefaultTypeInternal() {}
  union {
    classical_base_combine _instance;
  };
};

PROTOBUF_ATTRIBUTE_NO_DESTROY PROTOBUF_CONSTINIT
    PROTOBUF_ATTRIBUTE_INIT_PRIORITY1 classical_base_combineDefaultTypeInternal _classical_base_combine_default_instance_;
        template <typename>
PROTOBUF_CONSTEXPR Config::Config(::_pbi::ConstantInitialized)
    : _impl_{
      /*decltype(_impl_.configs_)*/ {},
      /*decltype(_impl_.base_configs_)*/ {},
      /*decltype(_impl_._cached_size_)*/ {},
    } {}
struct ConfigDefaultTypeInternal {
  PROTOBUF_CONSTEXPR ConfigDefaultTypeInternal() : _instance(::_pbi::ConstantInitialized{}) {}
  ~ConfigDefaultTypeInternal() {}
  union {
    Config _instance;
  };
};

PROTOBUF_ATTRIBUTE_NO_DESTROY PROTOBUF_CONSTINIT
    PROTOBUF_ATTRIBUTE_INIT_PRIORITY1 ConfigDefaultTypeInternal _Config_default_instance_;
}  // namespace pb
}  // namespace ClassicalCombines
static ::_pb::Metadata file_level_metadata_proto_2fconfig_5fClassicalCombines_2eproto[3];
static const ::_pb::EnumDescriptor* file_level_enum_descriptors_proto_2fconfig_5fClassicalCombines_2eproto[1];
static constexpr const ::_pb::ServiceDescriptor**
    file_level_service_descriptors_proto_2fconfig_5fClassicalCombines_2eproto = nullptr;
const ::uint32_t TableStruct_proto_2fconfig_5fClassicalCombines_2eproto::offsets[] PROTOBUF_SECTION_VARIABLE(
    protodesc_cold) = {
    ~0u,  // no _has_bits_
    PROTOBUF_FIELD_OFFSET(::ClassicalCombines::pb::classical_combine_config, _internal_metadata_),
    ~0u,  // no _extensions_
    ~0u,  // no _oneof_case_
    ~0u,  // no _weak_field_map_
    ~0u,  // no _inlined_string_donated_
    ~0u,  // no _split_
    ~0u,  // no sizeof(Split)
    PROTOBUF_FIELD_OFFSET(::ClassicalCombines::pb::classical_combine_config, _impl_.id_),
    PROTOBUF_FIELD_OFFSET(::ClassicalCombines::pb::classical_combine_config, _impl_.controlflag_),
    PROTOBUF_FIELD_OFFSET(::ClassicalCombines::pb::classical_combine_config, _impl_.rivaltype_),
    PROTOBUF_FIELD_OFFSET(::ClassicalCombines::pb::classical_combine_config, _impl_.combine0_),
    PROTOBUF_FIELD_OFFSET(::ClassicalCombines::pb::classical_combine_config, _impl_.combine1_),
    PROTOBUF_FIELD_OFFSET(::ClassicalCombines::pb::classical_combine_config, _impl_.combine2_),
    PROTOBUF_FIELD_OFFSET(::ClassicalCombines::pb::classical_combine_config, _impl_.remainbigcount_),
    ~0u,  // no _has_bits_
    PROTOBUF_FIELD_OFFSET(::ClassicalCombines::pb::classical_base_combine, _internal_metadata_),
    ~0u,  // no _extensions_
    ~0u,  // no _oneof_case_
    ~0u,  // no _weak_field_map_
    ~0u,  // no _inlined_string_donated_
    ~0u,  // no _split_
    ~0u,  // no sizeof(Split)
    PROTOBUF_FIELD_OFFSET(::ClassicalCombines::pb::classical_base_combine, _impl_.bigcount_),
    PROTOBUF_FIELD_OFFSET(::ClassicalCombines::pb::classical_base_combine, _impl_.bombcount_),
    PROTOBUF_FIELD_OFFSET(::ClassicalCombines::pb::classical_base_combine, _impl_.triplecount_),
    PROTOBUF_FIELD_OFFSET(::ClassicalCombines::pb::classical_base_combine, _impl_.paircount_),
    PROTOBUF_FIELD_OFFSET(::ClassicalCombines::pb::classical_base_combine, _impl_.singlecount_),
    ~0u,  // no _has_bits_
    PROTOBUF_FIELD_OFFSET(::ClassicalCombines::pb::Config, _internal_metadata_),
    ~0u,  // no _extensions_
    ~0u,  // no _oneof_case_
    ~0u,  // no _weak_field_map_
    ~0u,  // no _inlined_string_donated_
    ~0u,  // no _split_
    ~0u,  // no sizeof(Split)
    PROTOBUF_FIELD_OFFSET(::ClassicalCombines::pb::Config, _impl_.configs_),
    PROTOBUF_FIELD_OFFSET(::ClassicalCombines::pb::Config, _impl_.base_configs_),
};

static const ::_pbi::MigrationSchema
    schemas[] PROTOBUF_SECTION_VARIABLE(protodesc_cold) = {
        {0, -1, -1, sizeof(::ClassicalCombines::pb::classical_combine_config)},
        {15, -1, -1, sizeof(::ClassicalCombines::pb::classical_base_combine)},
        {28, -1, -1, sizeof(::ClassicalCombines::pb::Config)},
};

static const ::_pb::Message* const file_default_instances[] = {
    &::ClassicalCombines::pb::_classical_combine_config_default_instance_._instance,
    &::ClassicalCombines::pb::_classical_base_combine_default_instance_._instance,
    &::ClassicalCombines::pb::_Config_default_instance_._instance,
};
const char descriptor_table_protodef_proto_2fconfig_5fClassicalCombines_2eproto[] PROTOBUF_SECTION_VARIABLE(protodesc_cold) = {
    "\n$proto/config_ClassicalCombines.proto\022\024"
    "ClassicalCombines.pb\"\234\001\n\030classical_combi"
    "ne_config\022\n\n\002ID\030\001 \001(\r\022\023\n\013ControlFlag\030\002 \001"
    "(\r\022\021\n\tRivalType\030\003 \001(\r\022\020\n\010Combine0\030\004 \001(\004\022"
    "\020\n\010Combine1\030\005 \001(\004\022\020\n\010Combine2\030\006 \001(\004\022\026\n\016R"
    "emainBigCount\030\007 \001(\r\"z\n\026classical_base_co"
    "mbine\022\020\n\010BigCount\030\001 \001(\r\022\021\n\tBombCount\030\002 \001"
    "(\r\022\023\n\013TripleCount\030\003 \001(\r\022\021\n\tPairCount\030\004 \001"
    "(\r\022\023\n\013SingleCount\030\005 \001(\r\"\215\001\n\006Config\022\?\n\007co"
    "nfigs\030\001 \003(\0132..ClassicalCombines.pb.class"
    "ical_combine_config\022B\n\014base_configs\030\002 \003("
    "\0132,.ClassicalCombines.pb.classical_base_"
    "combine*Y\n\tRivalType\022\021\n\rNORMAL_RIVAL_\020\000\022"
    "\024\n\020NORMAL_NO_RIVAL_\020\001\022\017\n\013RARE_RIVAL_\020\002\022\022"
    "\n\016RARE_NO_RIVAL_\020\003B\035Z\033proto/out/classica"
    "l_combineb\006proto3"
};
static ::absl::once_flag descriptor_table_proto_2fconfig_5fClassicalCombines_2eproto_once;
const ::_pbi::DescriptorTable descriptor_table_proto_2fconfig_5fClassicalCombines_2eproto = {
    false,
    false,
    617,
    descriptor_table_protodef_proto_2fconfig_5fClassicalCombines_2eproto,
    "proto/config_ClassicalCombines.proto",
    &descriptor_table_proto_2fconfig_5fClassicalCombines_2eproto_once,
    nullptr,
    0,
    3,
    schemas,
    file_default_instances,
    TableStruct_proto_2fconfig_5fClassicalCombines_2eproto::offsets,
    file_level_metadata_proto_2fconfig_5fClassicalCombines_2eproto,
    file_level_enum_descriptors_proto_2fconfig_5fClassicalCombines_2eproto,
    file_level_service_descriptors_proto_2fconfig_5fClassicalCombines_2eproto,
};

// This function exists to be marked as weak.
// It can significantly speed up compilation by breaking up LLVM's SCC
// in the .pb.cc translation units. Large translation units see a
// reduction of more than 35% of walltime for optimized builds. Without
// the weak attribute all the messages in the file, including all the
// vtables and everything they use become part of the same SCC through
// a cycle like:
// GetMetadata -> descriptor table -> default instances ->
//   vtables -> GetMetadata
// By adding a weak function here we break the connection from the
// individual vtables back into the descriptor table.
PROTOBUF_ATTRIBUTE_WEAK const ::_pbi::DescriptorTable* descriptor_table_proto_2fconfig_5fClassicalCombines_2eproto_getter() {
  return &descriptor_table_proto_2fconfig_5fClassicalCombines_2eproto;
}
// Force running AddDescriptors() at dynamic initialization time.
PROTOBUF_ATTRIBUTE_INIT_PRIORITY2
static ::_pbi::AddDescriptorsRunner dynamic_init_dummy_proto_2fconfig_5fClassicalCombines_2eproto(&descriptor_table_proto_2fconfig_5fClassicalCombines_2eproto);
namespace ClassicalCombines {
namespace pb {
const ::google::protobuf::EnumDescriptor* RivalType_descriptor() {
  ::google::protobuf::internal::AssignDescriptors(&descriptor_table_proto_2fconfig_5fClassicalCombines_2eproto);
  return file_level_enum_descriptors_proto_2fconfig_5fClassicalCombines_2eproto[0];
}
bool RivalType_IsValid(int value) {
  switch (value) {
    case 0:
    case 1:
    case 2:
    case 3:
      return true;
    default:
      return false;
  }
}
// ===================================================================

class classical_combine_config::_Internal {
 public:
};

classical_combine_config::classical_combine_config(::google::protobuf::Arena* arena)
    : ::google::protobuf::Message(arena) {
  SharedCtor(arena);
  // @@protoc_insertion_point(arena_constructor:ClassicalCombines.pb.classical_combine_config)
}
classical_combine_config::classical_combine_config(const classical_combine_config& from)
    : ::google::protobuf::Message(), _impl_(from._impl_) {
  _internal_metadata_.MergeFrom<::google::protobuf::UnknownFieldSet>(
      from._internal_metadata_);
  // @@protoc_insertion_point(copy_constructor:ClassicalCombines.pb.classical_combine_config)
}
inline void classical_combine_config::SharedCtor(::_pb::Arena* arena) {
  (void)arena;
  new (&_impl_) Impl_{
      decltype(_impl_.id_){0u},
      decltype(_impl_.controlflag_){0u},
      decltype(_impl_.combine0_){::uint64_t{0u}},
      decltype(_impl_.combine1_){::uint64_t{0u}},
      decltype(_impl_.rivaltype_){0u},
      decltype(_impl_.remainbigcount_){0u},
      decltype(_impl_.combine2_){::uint64_t{0u}},
      /*decltype(_impl_._cached_size_)*/ {},
  };
}
classical_combine_config::~classical_combine_config() {
  // @@protoc_insertion_point(destructor:ClassicalCombines.pb.classical_combine_config)
  _internal_metadata_.Delete<::google::protobuf::UnknownFieldSet>();
  SharedDtor();
}
inline void classical_combine_config::SharedDtor() {
  ABSL_DCHECK(GetArenaForAllocation() == nullptr);
}
void classical_combine_config::SetCachedSize(int size) const {
  _impl_._cached_size_.Set(size);
}

PROTOBUF_NOINLINE void classical_combine_config::Clear() {
// @@protoc_insertion_point(message_clear_start:ClassicalCombines.pb.classical_combine_config)
  ::uint32_t cached_has_bits = 0;
  // Prevent compiler warnings about cached_has_bits being unused
  (void) cached_has_bits;

  ::memset(&_impl_.id_, 0, static_cast<::size_t>(
      reinterpret_cast<char*>(&_impl_.combine2_) -
      reinterpret_cast<char*>(&_impl_.id_)) + sizeof(_impl_.combine2_));
  _internal_metadata_.Clear<::google::protobuf::UnknownFieldSet>();
}

const char* classical_combine_config::_InternalParse(
    const char* ptr, ::_pbi::ParseContext* ctx) {
  ptr = ::_pbi::TcParser::ParseLoop(this, ptr, ctx, &_table_.header);
  return ptr;
}


PROTOBUF_CONSTINIT PROTOBUF_ATTRIBUTE_INIT_PRIORITY1
const ::_pbi::TcParseTable<3, 7, 0, 0, 2> classical_combine_config::_table_ = {
  {
    0,  // no _has_bits_
    0, // no _extensions_
    7, 56,  // max_field_number, fast_idx_mask
    offsetof(decltype(_table_), field_lookup_table),
    4294967168,  // skipmap
    offsetof(decltype(_table_), field_entries),
    7,  // num_field_entries
    0,  // num_aux_entries
    offsetof(decltype(_table_), field_names),  // no aux_entries
    &_classical_combine_config_default_instance_._instance,
    ::_pbi::TcParser::GenericFallback,  // fallback
  }, {{
    {::_pbi::TcParser::MiniParse, {}},
    // uint32 ID = 1;
    {::_pbi::TcParser::SingularVarintNoZag1<::uint32_t, offsetof(classical_combine_config, _impl_.id_), 63>(),
     {8, 63, 0, PROTOBUF_FIELD_OFFSET(classical_combine_config, _impl_.id_)}},
    // uint32 ControlFlag = 2;
    {::_pbi::TcParser::SingularVarintNoZag1<::uint32_t, offsetof(classical_combine_config, _impl_.controlflag_), 63>(),
     {16, 63, 0, PROTOBUF_FIELD_OFFSET(classical_combine_config, _impl_.controlflag_)}},
    // uint32 RivalType = 3;
    {::_pbi::TcParser::SingularVarintNoZag1<::uint32_t, offsetof(classical_combine_config, _impl_.rivaltype_), 63>(),
     {24, 63, 0, PROTOBUF_FIELD_OFFSET(classical_combine_config, _impl_.rivaltype_)}},
    // uint64 Combine0 = 4;
    {::_pbi::TcParser::SingularVarintNoZag1<::uint64_t, offsetof(classical_combine_config, _impl_.combine0_), 63>(),
     {32, 63, 0, PROTOBUF_FIELD_OFFSET(classical_combine_config, _impl_.combine0_)}},
    // uint64 Combine1 = 5;
    {::_pbi::TcParser::SingularVarintNoZag1<::uint64_t, offsetof(classical_combine_config, _impl_.combine1_), 63>(),
     {40, 63, 0, PROTOBUF_FIELD_OFFSET(classical_combine_config, _impl_.combine1_)}},
    // uint64 Combine2 = 6;
    {::_pbi::TcParser::SingularVarintNoZag1<::uint64_t, offsetof(classical_combine_config, _impl_.combine2_), 63>(),
     {48, 63, 0, PROTOBUF_FIELD_OFFSET(classical_combine_config, _impl_.combine2_)}},
    // uint32 RemainBigCount = 7;
    {::_pbi::TcParser::SingularVarintNoZag1<::uint32_t, offsetof(classical_combine_config, _impl_.remainbigcount_), 63>(),
     {56, 63, 0, PROTOBUF_FIELD_OFFSET(classical_combine_config, _impl_.remainbigcount_)}},
  }}, {{
    65535, 65535
  }}, {{
    // uint32 ID = 1;
    {PROTOBUF_FIELD_OFFSET(classical_combine_config, _impl_.id_), 0, 0,
    (0 | ::_fl::kFcSingular | ::_fl::kUInt32)},
    // uint32 ControlFlag = 2;
    {PROTOBUF_FIELD_OFFSET(classical_combine_config, _impl_.controlflag_), 0, 0,
    (0 | ::_fl::kFcSingular | ::_fl::kUInt32)},
    // uint32 RivalType = 3;
    {PROTOBUF_FIELD_OFFSET(classical_combine_config, _impl_.rivaltype_), 0, 0,
    (0 | ::_fl::kFcSingular | ::_fl::kUInt32)},
    // uint64 Combine0 = 4;
    {PROTOBUF_FIELD_OFFSET(classical_combine_config, _impl_.combine0_), 0, 0,
    (0 | ::_fl::kFcSingular | ::_fl::kUInt64)},
    // uint64 Combine1 = 5;
    {PROTOBUF_FIELD_OFFSET(classical_combine_config, _impl_.combine1_), 0, 0,
    (0 | ::_fl::kFcSingular | ::_fl::kUInt64)},
    // uint64 Combine2 = 6;
    {PROTOBUF_FIELD_OFFSET(classical_combine_config, _impl_.combine2_), 0, 0,
    (0 | ::_fl::kFcSingular | ::_fl::kUInt64)},
    // uint32 RemainBigCount = 7;
    {PROTOBUF_FIELD_OFFSET(classical_combine_config, _impl_.remainbigcount_), 0, 0,
    (0 | ::_fl::kFcSingular | ::_fl::kUInt32)},
  }},
  // no aux_entries
  {{
  }},
};

::uint8_t* classical_combine_config::_InternalSerialize(
    ::uint8_t* target,
    ::google::protobuf::io::EpsCopyOutputStream* stream) const {
  // @@protoc_insertion_point(serialize_to_array_start:ClassicalCombines.pb.classical_combine_config)
  ::uint32_t cached_has_bits = 0;
  (void)cached_has_bits;

  // uint32 ID = 1;
  if (this->_internal_id() != 0) {
    target = stream->EnsureSpace(target);
    target = ::_pbi::WireFormatLite::WriteUInt32ToArray(
        1, this->_internal_id(), target);
  }

  // uint32 ControlFlag = 2;
  if (this->_internal_controlflag() != 0) {
    target = stream->EnsureSpace(target);
    target = ::_pbi::WireFormatLite::WriteUInt32ToArray(
        2, this->_internal_controlflag(), target);
  }

  // uint32 RivalType = 3;
  if (this->_internal_rivaltype() != 0) {
    target = stream->EnsureSpace(target);
    target = ::_pbi::WireFormatLite::WriteUInt32ToArray(
        3, this->_internal_rivaltype(), target);
  }

  // uint64 Combine0 = 4;
  if (this->_internal_combine0() != 0) {
    target = stream->EnsureSpace(target);
    target = ::_pbi::WireFormatLite::WriteUInt64ToArray(
        4, this->_internal_combine0(), target);
  }

  // uint64 Combine1 = 5;
  if (this->_internal_combine1() != 0) {
    target = stream->EnsureSpace(target);
    target = ::_pbi::WireFormatLite::WriteUInt64ToArray(
        5, this->_internal_combine1(), target);
  }

  // uint64 Combine2 = 6;
  if (this->_internal_combine2() != 0) {
    target = stream->EnsureSpace(target);
    target = ::_pbi::WireFormatLite::WriteUInt64ToArray(
        6, this->_internal_combine2(), target);
  }

  // uint32 RemainBigCount = 7;
  if (this->_internal_remainbigcount() != 0) {
    target = stream->EnsureSpace(target);
    target = ::_pbi::WireFormatLite::WriteUInt32ToArray(
        7, this->_internal_remainbigcount(), target);
  }

  if (PROTOBUF_PREDICT_FALSE(_internal_metadata_.have_unknown_fields())) {
    target =
        ::_pbi::WireFormat::InternalSerializeUnknownFieldsToArray(
            _internal_metadata_.unknown_fields<::google::protobuf::UnknownFieldSet>(::google::protobuf::UnknownFieldSet::default_instance), target, stream);
  }
  // @@protoc_insertion_point(serialize_to_array_end:ClassicalCombines.pb.classical_combine_config)
  return target;
}

::size_t classical_combine_config::ByteSizeLong() const {
// @@protoc_insertion_point(message_byte_size_start:ClassicalCombines.pb.classical_combine_config)
  ::size_t total_size = 0;

  ::uint32_t cached_has_bits = 0;
  // Prevent compiler warnings about cached_has_bits being unused
  (void) cached_has_bits;

  // uint32 ID = 1;
  if (this->_internal_id() != 0) {
    total_size += ::_pbi::WireFormatLite::UInt32SizePlusOne(
        this->_internal_id());
  }

  // uint32 ControlFlag = 2;
  if (this->_internal_controlflag() != 0) {
    total_size += ::_pbi::WireFormatLite::UInt32SizePlusOne(
        this->_internal_controlflag());
  }

  // uint64 Combine0 = 4;
  if (this->_internal_combine0() != 0) {
    total_size += ::_pbi::WireFormatLite::UInt64SizePlusOne(
        this->_internal_combine0());
  }

  // uint64 Combine1 = 5;
  if (this->_internal_combine1() != 0) {
    total_size += ::_pbi::WireFormatLite::UInt64SizePlusOne(
        this->_internal_combine1());
  }

  // uint32 RivalType = 3;
  if (this->_internal_rivaltype() != 0) {
    total_size += ::_pbi::WireFormatLite::UInt32SizePlusOne(
        this->_internal_rivaltype());
  }

  // uint32 RemainBigCount = 7;
  if (this->_internal_remainbigcount() != 0) {
    total_size += ::_pbi::WireFormatLite::UInt32SizePlusOne(
        this->_internal_remainbigcount());
  }

  // uint64 Combine2 = 6;
  if (this->_internal_combine2() != 0) {
    total_size += ::_pbi::WireFormatLite::UInt64SizePlusOne(
        this->_internal_combine2());
  }

  return MaybeComputeUnknownFieldsSize(total_size, &_impl_._cached_size_);
}

const ::google::protobuf::Message::ClassData classical_combine_config::_class_data_ = {
    ::google::protobuf::Message::CopyWithSourceCheck,
    classical_combine_config::MergeImpl
};
const ::google::protobuf::Message::ClassData*classical_combine_config::GetClassData() const { return &_class_data_; }


void classical_combine_config::MergeImpl(::google::protobuf::Message& to_msg, const ::google::protobuf::Message& from_msg) {
  auto* const _this = static_cast<classical_combine_config*>(&to_msg);
  auto& from = static_cast<const classical_combine_config&>(from_msg);
  // @@protoc_insertion_point(class_specific_merge_from_start:ClassicalCombines.pb.classical_combine_config)
  ABSL_DCHECK_NE(&from, _this);
  ::uint32_t cached_has_bits = 0;
  (void) cached_has_bits;

  if (from._internal_id() != 0) {
    _this->_internal_set_id(from._internal_id());
  }
  if (from._internal_controlflag() != 0) {
    _this->_internal_set_controlflag(from._internal_controlflag());
  }
  if (from._internal_combine0() != 0) {
    _this->_internal_set_combine0(from._internal_combine0());
  }
  if (from._internal_combine1() != 0) {
    _this->_internal_set_combine1(from._internal_combine1());
  }
  if (from._internal_rivaltype() != 0) {
    _this->_internal_set_rivaltype(from._internal_rivaltype());
  }
  if (from._internal_remainbigcount() != 0) {
    _this->_internal_set_remainbigcount(from._internal_remainbigcount());
  }
  if (from._internal_combine2() != 0) {
    _this->_internal_set_combine2(from._internal_combine2());
  }
  _this->_internal_metadata_.MergeFrom<::google::protobuf::UnknownFieldSet>(from._internal_metadata_);
}

void classical_combine_config::CopyFrom(const classical_combine_config& from) {
// @@protoc_insertion_point(class_specific_copy_from_start:ClassicalCombines.pb.classical_combine_config)
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}

PROTOBUF_NOINLINE bool classical_combine_config::IsInitialized() const {
  return true;
}

void classical_combine_config::InternalSwap(classical_combine_config* other) {
  using std::swap;
  _internal_metadata_.InternalSwap(&other->_internal_metadata_);
  ::google::protobuf::internal::memswap<
      PROTOBUF_FIELD_OFFSET(classical_combine_config, _impl_.combine2_)
      + sizeof(classical_combine_config::_impl_.combine2_)
      - PROTOBUF_FIELD_OFFSET(classical_combine_config, _impl_.id_)>(
          reinterpret_cast<char*>(&_impl_.id_),
          reinterpret_cast<char*>(&other->_impl_.id_));
}

::google::protobuf::Metadata classical_combine_config::GetMetadata() const {
  return ::_pbi::AssignDescriptors(
      &descriptor_table_proto_2fconfig_5fClassicalCombines_2eproto_getter, &descriptor_table_proto_2fconfig_5fClassicalCombines_2eproto_once,
      file_level_metadata_proto_2fconfig_5fClassicalCombines_2eproto[0]);
}
// ===================================================================

class classical_base_combine::_Internal {
 public:
};

classical_base_combine::classical_base_combine(::google::protobuf::Arena* arena)
    : ::google::protobuf::Message(arena) {
  SharedCtor(arena);
  // @@protoc_insertion_point(arena_constructor:ClassicalCombines.pb.classical_base_combine)
}
classical_base_combine::classical_base_combine(const classical_base_combine& from)
    : ::google::protobuf::Message(), _impl_(from._impl_) {
  _internal_metadata_.MergeFrom<::google::protobuf::UnknownFieldSet>(
      from._internal_metadata_);
  // @@protoc_insertion_point(copy_constructor:ClassicalCombines.pb.classical_base_combine)
}
inline void classical_base_combine::SharedCtor(::_pb::Arena* arena) {
  (void)arena;
  new (&_impl_) Impl_{
      decltype(_impl_.bigcount_){0u},
      decltype(_impl_.bombcount_){0u},
      decltype(_impl_.triplecount_){0u},
      decltype(_impl_.paircount_){0u},
      decltype(_impl_.singlecount_){0u},
      /*decltype(_impl_._cached_size_)*/ {},
  };
}
classical_base_combine::~classical_base_combine() {
  // @@protoc_insertion_point(destructor:ClassicalCombines.pb.classical_base_combine)
  _internal_metadata_.Delete<::google::protobuf::UnknownFieldSet>();
  SharedDtor();
}
inline void classical_base_combine::SharedDtor() {
  ABSL_DCHECK(GetArenaForAllocation() == nullptr);
}
void classical_base_combine::SetCachedSize(int size) const {
  _impl_._cached_size_.Set(size);
}

PROTOBUF_NOINLINE void classical_base_combine::Clear() {
// @@protoc_insertion_point(message_clear_start:ClassicalCombines.pb.classical_base_combine)
  ::uint32_t cached_has_bits = 0;
  // Prevent compiler warnings about cached_has_bits being unused
  (void) cached_has_bits;

  ::memset(&_impl_.bigcount_, 0, static_cast<::size_t>(
      reinterpret_cast<char*>(&_impl_.singlecount_) -
      reinterpret_cast<char*>(&_impl_.bigcount_)) + sizeof(_impl_.singlecount_));
  _internal_metadata_.Clear<::google::protobuf::UnknownFieldSet>();
}

const char* classical_base_combine::_InternalParse(
    const char* ptr, ::_pbi::ParseContext* ctx) {
  ptr = ::_pbi::TcParser::ParseLoop(this, ptr, ctx, &_table_.header);
  return ptr;
}


PROTOBUF_CONSTINIT PROTOBUF_ATTRIBUTE_INIT_PRIORITY1
const ::_pbi::TcParseTable<3, 5, 0, 0, 2> classical_base_combine::_table_ = {
  {
    0,  // no _has_bits_
    0, // no _extensions_
    5, 56,  // max_field_number, fast_idx_mask
    offsetof(decltype(_table_), field_lookup_table),
    4294967264,  // skipmap
    offsetof(decltype(_table_), field_entries),
    5,  // num_field_entries
    0,  // num_aux_entries
    offsetof(decltype(_table_), field_names),  // no aux_entries
    &_classical_base_combine_default_instance_._instance,
    ::_pbi::TcParser::GenericFallback,  // fallback
  }, {{
    {::_pbi::TcParser::MiniParse, {}},
    // uint32 BigCount = 1;
    {::_pbi::TcParser::SingularVarintNoZag1<::uint32_t, offsetof(classical_base_combine, _impl_.bigcount_), 63>(),
     {8, 63, 0, PROTOBUF_FIELD_OFFSET(classical_base_combine, _impl_.bigcount_)}},
    // uint32 BombCount = 2;
    {::_pbi::TcParser::SingularVarintNoZag1<::uint32_t, offsetof(classical_base_combine, _impl_.bombcount_), 63>(),
     {16, 63, 0, PROTOBUF_FIELD_OFFSET(classical_base_combine, _impl_.bombcount_)}},
    // uint32 TripleCount = 3;
    {::_pbi::TcParser::SingularVarintNoZag1<::uint32_t, offsetof(classical_base_combine, _impl_.triplecount_), 63>(),
     {24, 63, 0, PROTOBUF_FIELD_OFFSET(classical_base_combine, _impl_.triplecount_)}},
    // uint32 PairCount = 4;
    {::_pbi::TcParser::SingularVarintNoZag1<::uint32_t, offsetof(classical_base_combine, _impl_.paircount_), 63>(),
     {32, 63, 0, PROTOBUF_FIELD_OFFSET(classical_base_combine, _impl_.paircount_)}},
    // uint32 SingleCount = 5;
    {::_pbi::TcParser::SingularVarintNoZag1<::uint32_t, offsetof(classical_base_combine, _impl_.singlecount_), 63>(),
     {40, 63, 0, PROTOBUF_FIELD_OFFSET(classical_base_combine, _impl_.singlecount_)}},
    {::_pbi::TcParser::MiniParse, {}},
    {::_pbi::TcParser::MiniParse, {}},
  }}, {{
    65535, 65535
  }}, {{
    // uint32 BigCount = 1;
    {PROTOBUF_FIELD_OFFSET(classical_base_combine, _impl_.bigcount_), 0, 0,
    (0 | ::_fl::kFcSingular | ::_fl::kUInt32)},
    // uint32 BombCount = 2;
    {PROTOBUF_FIELD_OFFSET(classical_base_combine, _impl_.bombcount_), 0, 0,
    (0 | ::_fl::kFcSingular | ::_fl::kUInt32)},
    // uint32 TripleCount = 3;
    {PROTOBUF_FIELD_OFFSET(classical_base_combine, _impl_.triplecount_), 0, 0,
    (0 | ::_fl::kFcSingular | ::_fl::kUInt32)},
    // uint32 PairCount = 4;
    {PROTOBUF_FIELD_OFFSET(classical_base_combine, _impl_.paircount_), 0, 0,
    (0 | ::_fl::kFcSingular | ::_fl::kUInt32)},
    // uint32 SingleCount = 5;
    {PROTOBUF_FIELD_OFFSET(classical_base_combine, _impl_.singlecount_), 0, 0,
    (0 | ::_fl::kFcSingular | ::_fl::kUInt32)},
  }},
  // no aux_entries
  {{
  }},
};

::uint8_t* classical_base_combine::_InternalSerialize(
    ::uint8_t* target,
    ::google::protobuf::io::EpsCopyOutputStream* stream) const {
  // @@protoc_insertion_point(serialize_to_array_start:ClassicalCombines.pb.classical_base_combine)
  ::uint32_t cached_has_bits = 0;
  (void)cached_has_bits;

  // uint32 BigCount = 1;
  if (this->_internal_bigcount() != 0) {
    target = stream->EnsureSpace(target);
    target = ::_pbi::WireFormatLite::WriteUInt32ToArray(
        1, this->_internal_bigcount(), target);
  }

  // uint32 BombCount = 2;
  if (this->_internal_bombcount() != 0) {
    target = stream->EnsureSpace(target);
    target = ::_pbi::WireFormatLite::WriteUInt32ToArray(
        2, this->_internal_bombcount(), target);
  }

  // uint32 TripleCount = 3;
  if (this->_internal_triplecount() != 0) {
    target = stream->EnsureSpace(target);
    target = ::_pbi::WireFormatLite::WriteUInt32ToArray(
        3, this->_internal_triplecount(), target);
  }

  // uint32 PairCount = 4;
  if (this->_internal_paircount() != 0) {
    target = stream->EnsureSpace(target);
    target = ::_pbi::WireFormatLite::WriteUInt32ToArray(
        4, this->_internal_paircount(), target);
  }

  // uint32 SingleCount = 5;
  if (this->_internal_singlecount() != 0) {
    target = stream->EnsureSpace(target);
    target = ::_pbi::WireFormatLite::WriteUInt32ToArray(
        5, this->_internal_singlecount(), target);
  }

  if (PROTOBUF_PREDICT_FALSE(_internal_metadata_.have_unknown_fields())) {
    target =
        ::_pbi::WireFormat::InternalSerializeUnknownFieldsToArray(
            _internal_metadata_.unknown_fields<::google::protobuf::UnknownFieldSet>(::google::protobuf::UnknownFieldSet::default_instance), target, stream);
  }
  // @@protoc_insertion_point(serialize_to_array_end:ClassicalCombines.pb.classical_base_combine)
  return target;
}

::size_t classical_base_combine::ByteSizeLong() const {
// @@protoc_insertion_point(message_byte_size_start:ClassicalCombines.pb.classical_base_combine)
  ::size_t total_size = 0;

  ::uint32_t cached_has_bits = 0;
  // Prevent compiler warnings about cached_has_bits being unused
  (void) cached_has_bits;

  // uint32 BigCount = 1;
  if (this->_internal_bigcount() != 0) {
    total_size += ::_pbi::WireFormatLite::UInt32SizePlusOne(
        this->_internal_bigcount());
  }

  // uint32 BombCount = 2;
  if (this->_internal_bombcount() != 0) {
    total_size += ::_pbi::WireFormatLite::UInt32SizePlusOne(
        this->_internal_bombcount());
  }

  // uint32 TripleCount = 3;
  if (this->_internal_triplecount() != 0) {
    total_size += ::_pbi::WireFormatLite::UInt32SizePlusOne(
        this->_internal_triplecount());
  }

  // uint32 PairCount = 4;
  if (this->_internal_paircount() != 0) {
    total_size += ::_pbi::WireFormatLite::UInt32SizePlusOne(
        this->_internal_paircount());
  }

  // uint32 SingleCount = 5;
  if (this->_internal_singlecount() != 0) {
    total_size += ::_pbi::WireFormatLite::UInt32SizePlusOne(
        this->_internal_singlecount());
  }

  return MaybeComputeUnknownFieldsSize(total_size, &_impl_._cached_size_);
}

const ::google::protobuf::Message::ClassData classical_base_combine::_class_data_ = {
    ::google::protobuf::Message::CopyWithSourceCheck,
    classical_base_combine::MergeImpl
};
const ::google::protobuf::Message::ClassData*classical_base_combine::GetClassData() const { return &_class_data_; }


void classical_base_combine::MergeImpl(::google::protobuf::Message& to_msg, const ::google::protobuf::Message& from_msg) {
  auto* const _this = static_cast<classical_base_combine*>(&to_msg);
  auto& from = static_cast<const classical_base_combine&>(from_msg);
  // @@protoc_insertion_point(class_specific_merge_from_start:ClassicalCombines.pb.classical_base_combine)
  ABSL_DCHECK_NE(&from, _this);
  ::uint32_t cached_has_bits = 0;
  (void) cached_has_bits;

  if (from._internal_bigcount() != 0) {
    _this->_internal_set_bigcount(from._internal_bigcount());
  }
  if (from._internal_bombcount() != 0) {
    _this->_internal_set_bombcount(from._internal_bombcount());
  }
  if (from._internal_triplecount() != 0) {
    _this->_internal_set_triplecount(from._internal_triplecount());
  }
  if (from._internal_paircount() != 0) {
    _this->_internal_set_paircount(from._internal_paircount());
  }
  if (from._internal_singlecount() != 0) {
    _this->_internal_set_singlecount(from._internal_singlecount());
  }
  _this->_internal_metadata_.MergeFrom<::google::protobuf::UnknownFieldSet>(from._internal_metadata_);
}

void classical_base_combine::CopyFrom(const classical_base_combine& from) {
// @@protoc_insertion_point(class_specific_copy_from_start:ClassicalCombines.pb.classical_base_combine)
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}

PROTOBUF_NOINLINE bool classical_base_combine::IsInitialized() const {
  return true;
}

void classical_base_combine::InternalSwap(classical_base_combine* other) {
  using std::swap;
  _internal_metadata_.InternalSwap(&other->_internal_metadata_);
  ::google::protobuf::internal::memswap<
      PROTOBUF_FIELD_OFFSET(classical_base_combine, _impl_.singlecount_)
      + sizeof(classical_base_combine::_impl_.singlecount_)
      - PROTOBUF_FIELD_OFFSET(classical_base_combine, _impl_.bigcount_)>(
          reinterpret_cast<char*>(&_impl_.bigcount_),
          reinterpret_cast<char*>(&other->_impl_.bigcount_));
}

::google::protobuf::Metadata classical_base_combine::GetMetadata() const {
  return ::_pbi::AssignDescriptors(
      &descriptor_table_proto_2fconfig_5fClassicalCombines_2eproto_getter, &descriptor_table_proto_2fconfig_5fClassicalCombines_2eproto_once,
      file_level_metadata_proto_2fconfig_5fClassicalCombines_2eproto[1]);
}
// ===================================================================

class Config::_Internal {
 public:
};

Config::Config(::google::protobuf::Arena* arena)
    : ::google::protobuf::Message(arena) {
  SharedCtor(arena);
  // @@protoc_insertion_point(arena_constructor:ClassicalCombines.pb.Config)
}
Config::Config(const Config& from) : ::google::protobuf::Message() {
  Config* const _this = this;
  (void)_this;
  new (&_impl_) Impl_{
      decltype(_impl_.configs_){from._impl_.configs_},
      decltype(_impl_.base_configs_){from._impl_.base_configs_},
      /*decltype(_impl_._cached_size_)*/ {},
  };
  _internal_metadata_.MergeFrom<::google::protobuf::UnknownFieldSet>(
      from._internal_metadata_);

  // @@protoc_insertion_point(copy_constructor:ClassicalCombines.pb.Config)
}
inline void Config::SharedCtor(::_pb::Arena* arena) {
  (void)arena;
  new (&_impl_) Impl_{
      decltype(_impl_.configs_){arena},
      decltype(_impl_.base_configs_){arena},
      /*decltype(_impl_._cached_size_)*/ {},
  };
}
Config::~Config() {
  // @@protoc_insertion_point(destructor:ClassicalCombines.pb.Config)
  _internal_metadata_.Delete<::google::protobuf::UnknownFieldSet>();
  SharedDtor();
}
inline void Config::SharedDtor() {
  ABSL_DCHECK(GetArenaForAllocation() == nullptr);
  _impl_.configs_.~RepeatedPtrField();
  _impl_.base_configs_.~RepeatedPtrField();
}
void Config::SetCachedSize(int size) const {
  _impl_._cached_size_.Set(size);
}

PROTOBUF_NOINLINE void Config::Clear() {
// @@protoc_insertion_point(message_clear_start:ClassicalCombines.pb.Config)
  ::uint32_t cached_has_bits = 0;
  // Prevent compiler warnings about cached_has_bits being unused
  (void) cached_has_bits;

  _internal_mutable_configs()->Clear();
  _internal_mutable_base_configs()->Clear();
  _internal_metadata_.Clear<::google::protobuf::UnknownFieldSet>();
}

const char* Config::_InternalParse(
    const char* ptr, ::_pbi::ParseContext* ctx) {
  ptr = ::_pbi::TcParser::ParseLoop(this, ptr, ctx, &_table_.header);
  return ptr;
}


PROTOBUF_CONSTINIT PROTOBUF_ATTRIBUTE_INIT_PRIORITY1
const ::_pbi::TcParseTable<1, 2, 2, 0, 2> Config::_table_ = {
  {
    0,  // no _has_bits_
    0, // no _extensions_
    2, 8,  // max_field_number, fast_idx_mask
    offsetof(decltype(_table_), field_lookup_table),
    4294967292,  // skipmap
    offsetof(decltype(_table_), field_entries),
    2,  // num_field_entries
    2,  // num_aux_entries
    offsetof(decltype(_table_), aux_entries),
    &_Config_default_instance_._instance,
    ::_pbi::TcParser::GenericFallback,  // fallback
  }, {{
    // repeated .ClassicalCombines.pb.classical_base_combine base_configs = 2;
    {::_pbi::TcParser::FastMtR1,
     {18, 63, 1, PROTOBUF_FIELD_OFFSET(Config, _impl_.base_configs_)}},
    // repeated .ClassicalCombines.pb.classical_combine_config configs = 1;
    {::_pbi::TcParser::FastMtR1,
     {10, 63, 0, PROTOBUF_FIELD_OFFSET(Config, _impl_.configs_)}},
  }}, {{
    65535, 65535
  }}, {{
    // repeated .ClassicalCombines.pb.classical_combine_config configs = 1;
    {PROTOBUF_FIELD_OFFSET(Config, _impl_.configs_), 0, 0,
    (0 | ::_fl::kFcRepeated | ::_fl::kMessage | ::_fl::kTvTable)},
    // repeated .ClassicalCombines.pb.classical_base_combine base_configs = 2;
    {PROTOBUF_FIELD_OFFSET(Config, _impl_.base_configs_), 0, 1,
    (0 | ::_fl::kFcRepeated | ::_fl::kMessage | ::_fl::kTvTable)},
  }}, {{
    {::_pbi::TcParser::GetTable<::ClassicalCombines::pb::classical_combine_config>()},
    {::_pbi::TcParser::GetTable<::ClassicalCombines::pb::classical_base_combine>()},
  }}, {{
  }},
};

::uint8_t* Config::_InternalSerialize(
    ::uint8_t* target,
    ::google::protobuf::io::EpsCopyOutputStream* stream) const {
  // @@protoc_insertion_point(serialize_to_array_start:ClassicalCombines.pb.Config)
  ::uint32_t cached_has_bits = 0;
  (void)cached_has_bits;

  // repeated .ClassicalCombines.pb.classical_combine_config configs = 1;
  for (unsigned i = 0,
      n = static_cast<unsigned>(this->_internal_configs_size()); i < n; i++) {
    const auto& repfield = this->_internal_configs().Get(i);
    target = ::google::protobuf::internal::WireFormatLite::
        InternalWriteMessage(1, repfield, repfield.GetCachedSize(), target, stream);
  }

  // repeated .ClassicalCombines.pb.classical_base_combine base_configs = 2;
  for (unsigned i = 0,
      n = static_cast<unsigned>(this->_internal_base_configs_size()); i < n; i++) {
    const auto& repfield = this->_internal_base_configs().Get(i);
    target = ::google::protobuf::internal::WireFormatLite::
        InternalWriteMessage(2, repfield, repfield.GetCachedSize(), target, stream);
  }

  if (PROTOBUF_PREDICT_FALSE(_internal_metadata_.have_unknown_fields())) {
    target =
        ::_pbi::WireFormat::InternalSerializeUnknownFieldsToArray(
            _internal_metadata_.unknown_fields<::google::protobuf::UnknownFieldSet>(::google::protobuf::UnknownFieldSet::default_instance), target, stream);
  }
  // @@protoc_insertion_point(serialize_to_array_end:ClassicalCombines.pb.Config)
  return target;
}

::size_t Config::ByteSizeLong() const {
// @@protoc_insertion_point(message_byte_size_start:ClassicalCombines.pb.Config)
  ::size_t total_size = 0;

  ::uint32_t cached_has_bits = 0;
  // Prevent compiler warnings about cached_has_bits being unused
  (void) cached_has_bits;

  // repeated .ClassicalCombines.pb.classical_combine_config configs = 1;
  total_size += 1UL * this->_internal_configs_size();
  for (const auto& msg : this->_internal_configs()) {
    total_size +=
      ::google::protobuf::internal::WireFormatLite::MessageSize(msg);
  }
  // repeated .ClassicalCombines.pb.classical_base_combine base_configs = 2;
  total_size += 1UL * this->_internal_base_configs_size();
  for (const auto& msg : this->_internal_base_configs()) {
    total_size +=
      ::google::protobuf::internal::WireFormatLite::MessageSize(msg);
  }
  return MaybeComputeUnknownFieldsSize(total_size, &_impl_._cached_size_);
}

const ::google::protobuf::Message::ClassData Config::_class_data_ = {
    ::google::protobuf::Message::CopyWithSourceCheck,
    Config::MergeImpl
};
const ::google::protobuf::Message::ClassData*Config::GetClassData() const { return &_class_data_; }


void Config::MergeImpl(::google::protobuf::Message& to_msg, const ::google::protobuf::Message& from_msg) {
  auto* const _this = static_cast<Config*>(&to_msg);
  auto& from = static_cast<const Config&>(from_msg);
  // @@protoc_insertion_point(class_specific_merge_from_start:ClassicalCombines.pb.Config)
  ABSL_DCHECK_NE(&from, _this);
  ::uint32_t cached_has_bits = 0;
  (void) cached_has_bits;

  _this->_internal_mutable_configs()->MergeFrom(from._internal_configs());
  _this->_internal_mutable_base_configs()->MergeFrom(from._internal_base_configs());
  _this->_internal_metadata_.MergeFrom<::google::protobuf::UnknownFieldSet>(from._internal_metadata_);
}

void Config::CopyFrom(const Config& from) {
// @@protoc_insertion_point(class_specific_copy_from_start:ClassicalCombines.pb.Config)
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}

PROTOBUF_NOINLINE bool Config::IsInitialized() const {
  return true;
}

void Config::InternalSwap(Config* other) {
  using std::swap;
  _internal_metadata_.InternalSwap(&other->_internal_metadata_);
  _impl_.configs_.InternalSwap(&other->_impl_.configs_);
  _impl_.base_configs_.InternalSwap(&other->_impl_.base_configs_);
}

::google::protobuf::Metadata Config::GetMetadata() const {
  return ::_pbi::AssignDescriptors(
      &descriptor_table_proto_2fconfig_5fClassicalCombines_2eproto_getter, &descriptor_table_proto_2fconfig_5fClassicalCombines_2eproto_once,
      file_level_metadata_proto_2fconfig_5fClassicalCombines_2eproto[2]);
}
// @@protoc_insertion_point(namespace_scope)
}  // namespace pb
}  // namespace ClassicalCombines
namespace google {
namespace protobuf {
}  // namespace protobuf
}  // namespace google
// @@protoc_insertion_point(global_scope)
#include "google/protobuf/port_undef.inc"
